# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Compiler-Design-Course/RCompiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Compiler-Design-Course/RCompiler/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Compiler-Design-Course/RCompiler/cmake-build-debug/CMakeFiles /mnt/d/Compiler-Design-Course/RCompiler/cmake-build-debug//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Compiler-Design-Course/RCompiler/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RCompiler

# Build rule for target.
RCompiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RCompiler
.PHONY : RCompiler

# fast build rule for target.
RCompiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/build
.PHONY : RCompiler/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/main.cpp.s
.PHONY : main.cpp.s

src/IR/IRBuilder.o: src/IR/IRBuilder.cpp.o
.PHONY : src/IR/IRBuilder.o

# target to build an object file
src/IR/IRBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/IR/IRBuilder.cpp.o
.PHONY : src/IR/IRBuilder.cpp.o

src/IR/IRBuilder.i: src/IR/IRBuilder.cpp.i
.PHONY : src/IR/IRBuilder.i

# target to preprocess a source file
src/IR/IRBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/IR/IRBuilder.cpp.i
.PHONY : src/IR/IRBuilder.cpp.i

src/IR/IRBuilder.s: src/IR/IRBuilder.cpp.s
.PHONY : src/IR/IRBuilder.s

# target to generate assembly for a file
src/IR/IRBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/IR/IRBuilder.cpp.s
.PHONY : src/IR/IRBuilder.cpp.s

src/Lexer/Lexer.o: src/Lexer/Lexer.cpp.o
.PHONY : src/Lexer/Lexer.o

# target to build an object file
src/Lexer/Lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Lexer/Lexer.cpp.o
.PHONY : src/Lexer/Lexer.cpp.o

src/Lexer/Lexer.i: src/Lexer/Lexer.cpp.i
.PHONY : src/Lexer/Lexer.i

# target to preprocess a source file
src/Lexer/Lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Lexer/Lexer.cpp.i
.PHONY : src/Lexer/Lexer.cpp.i

src/Lexer/Lexer.s: src/Lexer/Lexer.cpp.s
.PHONY : src/Lexer/Lexer.s

# target to generate assembly for a file
src/Lexer/Lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Lexer/Lexer.cpp.s
.PHONY : src/Lexer/Lexer.cpp.s

src/Lexer/Token.o: src/Lexer/Token.cpp.o
.PHONY : src/Lexer/Token.o

# target to build an object file
src/Lexer/Token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Lexer/Token.cpp.o
.PHONY : src/Lexer/Token.cpp.o

src/Lexer/Token.i: src/Lexer/Token.cpp.i
.PHONY : src/Lexer/Token.i

# target to preprocess a source file
src/Lexer/Token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Lexer/Token.cpp.i
.PHONY : src/Lexer/Token.cpp.i

src/Lexer/Token.s: src/Lexer/Token.cpp.s
.PHONY : src/Lexer/Token.s

# target to generate assembly for a file
src/Lexer/Token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Lexer/Token.cpp.s
.PHONY : src/Lexer/Token.cpp.s

src/Parser/Parser.o: src/Parser/Parser.cpp.o
.PHONY : src/Parser/Parser.o

# target to build an object file
src/Parser/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Parser/Parser.cpp.o
.PHONY : src/Parser/Parser.cpp.o

src/Parser/Parser.i: src/Parser/Parser.cpp.i
.PHONY : src/Parser/Parser.i

# target to preprocess a source file
src/Parser/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Parser/Parser.cpp.i
.PHONY : src/Parser/Parser.cpp.i

src/Parser/Parser.s: src/Parser/Parser.cpp.s
.PHONY : src/Parser/Parser.s

# target to generate assembly for a file
src/Parser/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Parser/Parser.cpp.s
.PHONY : src/Parser/Parser.cpp.s

src/Semantic/ConstEvaluator.o: src/Semantic/ConstEvaluator.cpp.o
.PHONY : src/Semantic/ConstEvaluator.o

# target to build an object file
src/Semantic/ConstEvaluator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/ConstEvaluator.cpp.o
.PHONY : src/Semantic/ConstEvaluator.cpp.o

src/Semantic/ConstEvaluator.i: src/Semantic/ConstEvaluator.cpp.i
.PHONY : src/Semantic/ConstEvaluator.i

# target to preprocess a source file
src/Semantic/ConstEvaluator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/ConstEvaluator.cpp.i
.PHONY : src/Semantic/ConstEvaluator.cpp.i

src/Semantic/ConstEvaluator.s: src/Semantic/ConstEvaluator.cpp.s
.PHONY : src/Semantic/ConstEvaluator.s

# target to generate assembly for a file
src/Semantic/ConstEvaluator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/ConstEvaluator.cpp.s
.PHONY : src/Semantic/ConstEvaluator.cpp.s

src/Semantic/ScopeManager.o: src/Semantic/ScopeManager.cpp.o
.PHONY : src/Semantic/ScopeManager.o

# target to build an object file
src/Semantic/ScopeManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/ScopeManager.cpp.o
.PHONY : src/Semantic/ScopeManager.cpp.o

src/Semantic/ScopeManager.i: src/Semantic/ScopeManager.cpp.i
.PHONY : src/Semantic/ScopeManager.i

# target to preprocess a source file
src/Semantic/ScopeManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/ScopeManager.cpp.i
.PHONY : src/Semantic/ScopeManager.cpp.i

src/Semantic/ScopeManager.s: src/Semantic/ScopeManager.cpp.s
.PHONY : src/Semantic/ScopeManager.s

# target to generate assembly for a file
src/Semantic/ScopeManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/ScopeManager.cpp.s
.PHONY : src/Semantic/ScopeManager.cpp.s

src/Semantic/SemanticChecker.o: src/Semantic/SemanticChecker.cpp.o
.PHONY : src/Semantic/SemanticChecker.o

# target to build an object file
src/Semantic/SemanticChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/SemanticChecker.cpp.o
.PHONY : src/Semantic/SemanticChecker.cpp.o

src/Semantic/SemanticChecker.i: src/Semantic/SemanticChecker.cpp.i
.PHONY : src/Semantic/SemanticChecker.i

# target to preprocess a source file
src/Semantic/SemanticChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/SemanticChecker.cpp.i
.PHONY : src/Semantic/SemanticChecker.cpp.i

src/Semantic/SemanticChecker.s: src/Semantic/SemanticChecker.cpp.s
.PHONY : src/Semantic/SemanticChecker.s

# target to generate assembly for a file
src/Semantic/SemanticChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/SemanticChecker.cpp.s
.PHONY : src/Semantic/SemanticChecker.cpp.s

src/Semantic/SymbolCollector.o: src/Semantic/SymbolCollector.cpp.o
.PHONY : src/Semantic/SymbolCollector.o

# target to build an object file
src/Semantic/SymbolCollector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/SymbolCollector.cpp.o
.PHONY : src/Semantic/SymbolCollector.cpp.o

src/Semantic/SymbolCollector.i: src/Semantic/SymbolCollector.cpp.i
.PHONY : src/Semantic/SymbolCollector.i

# target to preprocess a source file
src/Semantic/SymbolCollector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/SymbolCollector.cpp.i
.PHONY : src/Semantic/SymbolCollector.cpp.i

src/Semantic/SymbolCollector.s: src/Semantic/SymbolCollector.cpp.s
.PHONY : src/Semantic/SymbolCollector.s

# target to generate assembly for a file
src/Semantic/SymbolCollector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/SymbolCollector.cpp.s
.PHONY : src/Semantic/SymbolCollector.cpp.s

src/Semantic/SymbolManager.o: src/Semantic/SymbolManager.cpp.o
.PHONY : src/Semantic/SymbolManager.o

# target to build an object file
src/Semantic/SymbolManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/SymbolManager.cpp.o
.PHONY : src/Semantic/SymbolManager.cpp.o

src/Semantic/SymbolManager.i: src/Semantic/SymbolManager.cpp.i
.PHONY : src/Semantic/SymbolManager.i

# target to preprocess a source file
src/Semantic/SymbolManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/SymbolManager.cpp.i
.PHONY : src/Semantic/SymbolManager.cpp.i

src/Semantic/SymbolManager.s: src/Semantic/SymbolManager.cpp.s
.PHONY : src/Semantic/SymbolManager.s

# target to generate assembly for a file
src/Semantic/SymbolManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/SymbolManager.cpp.s
.PHONY : src/Semantic/SymbolManager.cpp.s

src/Semantic/Type.o: src/Semantic/Type.cpp.o
.PHONY : src/Semantic/Type.o

# target to build an object file
src/Semantic/Type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/Type.cpp.o
.PHONY : src/Semantic/Type.cpp.o

src/Semantic/Type.i: src/Semantic/Type.cpp.i
.PHONY : src/Semantic/Type.i

# target to preprocess a source file
src/Semantic/Type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/Type.cpp.i
.PHONY : src/Semantic/Type.cpp.i

src/Semantic/Type.s: src/Semantic/Type.cpp.s
.PHONY : src/Semantic/Type.s

# target to generate assembly for a file
src/Semantic/Type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RCompiler.dir/build.make CMakeFiles/RCompiler.dir/src/Semantic/Type.cpp.s
.PHONY : src/Semantic/Type.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RCompiler"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/IR/IRBuilder.o"
	@echo "... src/IR/IRBuilder.i"
	@echo "... src/IR/IRBuilder.s"
	@echo "... src/Lexer/Lexer.o"
	@echo "... src/Lexer/Lexer.i"
	@echo "... src/Lexer/Lexer.s"
	@echo "... src/Lexer/Token.o"
	@echo "... src/Lexer/Token.i"
	@echo "... src/Lexer/Token.s"
	@echo "... src/Parser/Parser.o"
	@echo "... src/Parser/Parser.i"
	@echo "... src/Parser/Parser.s"
	@echo "... src/Semantic/ConstEvaluator.o"
	@echo "... src/Semantic/ConstEvaluator.i"
	@echo "... src/Semantic/ConstEvaluator.s"
	@echo "... src/Semantic/ScopeManager.o"
	@echo "... src/Semantic/ScopeManager.i"
	@echo "... src/Semantic/ScopeManager.s"
	@echo "... src/Semantic/SemanticChecker.o"
	@echo "... src/Semantic/SemanticChecker.i"
	@echo "... src/Semantic/SemanticChecker.s"
	@echo "... src/Semantic/SymbolCollector.o"
	@echo "... src/Semantic/SymbolCollector.i"
	@echo "... src/Semantic/SymbolCollector.s"
	@echo "... src/Semantic/SymbolManager.o"
	@echo "... src/Semantic/SymbolManager.i"
	@echo "... src/Semantic/SymbolManager.s"
	@echo "... src/Semantic/Type.o"
	@echo "... src/Semantic/Type.i"
	@echo "... src/Semantic/Type.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

